FROM maven
RUN apt-get install git
CMD java -version
RUN git clone https://github.com/ankushugale1979/Altimetrik
RUN cd /Altimetrik/HelloWorld
CMD mvn clean package
RUN mkdir -p /app
COPY /Altimetrik/HelloWorld/target/*.jar /app